# SPDX-FileCopyrightText: 2024 Tomodachi94 and contributors
#
# SPDX-License-Identifier: MIT

version = 1

[[annotations]]
path = "poetry.lock"
SPDX-FileCopyrightText = "Tomodachi94 and contributors"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = "flake.lock"
SPDX-FileCopyrightText = "Tomodachi94 and contributors"
SPDX-License-Identifier = "CC0-1.0"
